---
- name: install nginx package
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: "{{ nginx_packages }}"
  when: ("ansible_os_family == 'Debian'")
  tags:
    nginx

- name: add nginx main configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_server_conf_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags:
    nginx


- name: add default virtual host nginx configuration
  template:
    src: default.j2
    dest: "{{ nginx_default_vhost_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags:
      nginx

- name: enable vhost nginx configuration
  file:
    src: "{{ nginx_default_vhost_filename }}"
    dest: "{{ nginx_sites_enabled_path }}/default"
    state: link
  when: "ansible_os_family == 'Debian'"
  notify: reload nginx
  tags:
      nginx


- name: set up default index page
  copy:
    src: index.html
    dest: "{{ nginx_document_root }}"
    owner: root
    group: root
    mode: 0644
#  notify: restart nginx
  tags:
      nginx
