# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  nginx_nodes = [{name: "nginx-node1"},
                 {name: "nginx-node2"}
                ]
  #nginx_nodes = (JSON.parse(File.read(File.join(File.dirname(__FILE__),"/config.json"))))

  nginx_nodes.each do |node|

     config.vm.define node[:name] do |nginxnode|

        nginxnode.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.name = node[:name]
            vb.memory = 512
        end

        nginxnode.vm.provider :aws do |aws,override|
            override.vm.box = "aws"
            aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
            aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
            aws.region="eu-central-1"
            aws.availability_zone="eu-central-1a"
            aws.ami="ami-47d93c28" #debian/jessie ami
            aws.keypair_name = "aw_user"
            aws.tags = {
                'Name' => node[:name]
            }
            override.ssh.username = "admin"
            override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PEM']
        end

        #provisioning with ansible
        nginxnode.vm.provision "ansible" do |ansible|
            ansible.playbook = "../site.yml"
            ansible.sudo = true
            ansible.host_key_checking = false
            ansible.verbose = "v"
            ansible.limit = "all"
            ansible.tags = "nginx"
        end
     end

  end
end
