---
- name: restart nginx
  service:
    name: "{{ nginx_daemon }}"
    state: restarted
  tags:
    nginx

- name: reload nginx
  service:
    name: "{{ nginx_daemon }}"
    state: reload
  tags:
    nginx